import * as E from './engine.js';
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let d,runs,evidence,b,tab='attributes',history=[],chatHistory=[],teamCode='',busy=false,revision=0;
let endpoint=localStorage.getItem('fc26-endpoint')||'';
const groups={'Pace':['Acceleration','SprintSpeed'],'Shooting':['AttackPositioning','Finishing','ShotPower','LongShots','Volleys','Penalties'],'Passing':['Vision','Crossing','FKAccuracy','ShortPassing','LongPassing','Curve'],'Ball control':['Agility','Balance','Reactions','BallControl','Dribbling','Composure'],'Defending':['Interceptions','Heading Accuracy','DefAwareness','StandingTackle','SlidingTackle'],'Physical':['Jumping','Stamina','Strength','Aggression']};
const status=t=>{$('#status').textContent=t;};
function remember(){history.push(structuredClone(b));if(history.length>40)history.shift();revision++;}
function change(fn){try{const next=structuredClone(b);fn(next);remember();b=next;render();}catch(e){status(e.message);}}
function commit(next){const errors=E.validate(d,next);if(errors.length)throw Error(errors.join(' '));remember();b=next;render();}
function options(items,value){return items.map(v=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(E.title(v))}</option>`).join('');}
function lock(k){return `<button class="lock ${b.locks.includes(k)?'locked':''}" data-lock="${esc(k)}" aria-label="${b.locks.includes(k)?'Unlock':'Lock'} ${esc(E.title(k))}" aria-pressed="${b.locks.includes(k)}">${b.locks.includes(k)?'●':'○'}</button>`;}
function render(){const a=E.archetype(d,b),used=E.spent(d,b),total=E.budget(d,b),f=E.facilities(d,b);$('#build-name').value=b.name;$('#undo').disabled=!history.length;
 $('#overview').innerHTML=`<div class="overview"><div class="card"><label for="archetype">ARCHETYPE</label><select id="archetype">${options(d.archetypes.map(a=>a.name),b.archetype)}</select><small>${esc(a.position)} · ${esc(a.basePlaystyle)} signature</small></div><div class="card"><label>ATTRIBUTE POINTS</label><div class="metric ${used>total?'error':'accent'}">${total-used}<small> / ${total} available</small></div><div class="progress"><span style="width:${Math.min(100,used/total*100)}%"></span></div></div><div class="card"><label for="level">PLAYER LEVEL</label><input id="level" aria-label="Player level" type="number" min="1" max="100" value="${b.level}"><small> ${E.slots(d,b)} regular · ${E.plusSlots(d,b)} signature + slots</small></div></div><div class="body-controls"><label>Height (cm)<input data-field="height" type="number" value="${b.height}"></label>${lock('height')}<label>Weight (kg)<input data-field="weight" type="number" value="${b.weight}"></label>${lock('weight')}<label>Body category<select data-field="gender">${options(['male','female'],b.gender)}</select></label><label>Skill moves<select data-field="skillMoves">${options(Array.from({length:a.skillMoveRating.max-a.skillMoveRating.base+1},(_,i)=>i+a.skillMoveRating.base),b.skillMoves)}</select></label><label>Weak foot<select data-field="weakFoot">${options(Array.from({length:a.weakFootRating.max-a.weakFootRating.base+1},(_,i)=>i+a.weakFootRating.base),b.weakFoot)}</select></label><span class="accelerate">${E.accelerate(d,b)}</span></div>`;
 const errors=E.validate(d,b);status(errors.length?errors.join(' '):'');
 $('#archetype').onchange=e=>change(n=>Object.assign(n,{...E.fresh(d,e.target.value,n.level),name:n.name,clubLevel:n.clubLevel,facilities:n.facilities,facilityMode:n.facilityMode}));
 $('#level').onchange=e=>change(n=>{const v=Number(e.target.value);if(!Number.isInteger(v)||v<1||v>100)throw Error('Level must be 1–100.');n.level=v;});
 document.querySelectorAll('[data-field]').forEach(el=>el.onchange=e=>change(n=>{const k=e.target.dataset.field,v=['gender'].includes(k)?e.target.value:Number(e.target.value);if(typeof v==='number'&&!Number.isInteger(v))throw Error('Use a whole number.');n[k]=v;}));
 let html='';
 if(tab==='attributes'){const effective=E.effective(d,b);html=`<p class="muted">Edit base attributes. Green figures include body and ${b.facilityMode==='planned'?'planned':'active'} facility effects; boosts do not unlock attribute-gated PlayStyles. ○ locks a choice against AI edits.</p><div class="attribute-grid">`+Object.entries(groups).map(([name,keys])=>`<section class="card group"><h3>${name}</h3>${keys.map(k=>{const r=a.attributeRanges[k],next=E.attributeCost(d,b,k,Math.min(r.max,b.attributes[k]+1))-E.attributeCost(d,b,k);return `<div class="attr"><label for="attr-${k.replaceAll(' ','')}"><span class="${r.isKeyAttribute?'key':''}">${esc(E.title(k))}${r.isKeyAttribute?' ✦':''}</span><br><small>${r.min}–${r.max} · +1 costs ${next} AP · <span class="accent">${effective[k]} in match</span></small></label><input id="attr-${k.replaceAll(' ','')}" data-attr="${esc(k)}" type="number" min="${r.min}" max="${r.max}" value="${b.attributes[k]}">${lock(k)}<input aria-label="${esc(E.title(k))} slider" data-attr="${esc(k)}" type="range" min="${r.min}" max="${r.max}" value="${b.attributes[k]}"></div>`;}).join('')}</section>`).join('')+'</div>';}
 if(tab==='playstyles'){html=`<div class="section-title"><h3>Regular PlayStyles · ${b.playstyles.length}/${E.slots(d,b)}</h3>${lock('playstyles')}</div><div class="cards">`+d.playstyles.map(p=>{const missing=E.requirements(b,p);return `<label class="choice"><input type="checkbox" data-style="${esc(p.name)}" ${b.playstyles.includes(p.name)?'checked':''}>${esc(E.title(p.name))}<small>${p.attributeRequirements.map(r=>`${esc(E.title(r.attribute))} ${r.minimumValue}`).join(' · ')}</small>${missing.length?'<small class="error">Requirements not met</small>':'<small class="accent">Available</small>'}</label>`;}).join('')+`</div><div class="section-title"><h3>Specialization</h3>${lock('specialization')}</div><select id="specialization"><option value="">None</option>${options(a.specializationPerks.map(s=>s.specializationName),b.specialization)}</select><div class="cards">${a.specializationPerks.map(s=>`<div class="choice"><strong>${esc(E.title(s.specializationName))}</strong><small>${s.attributeRequirements.map(r=>`${esc(E.title(r.attribute))} ${r.minimumValue}`).join(' · ')}</small><small>${esc(s.perkDescription)}</small></div>`).join('')}</div><div class="section-title"><h3>Signature PlayStyles+ · ${b.plus.length}/${E.plusSlots(d,b)}</h3>${lock('plus')}</div><div class="cards">${E.plusOptions(d,b).map(p=>`<label class="choice"><input type="checkbox" data-plus="${esc(p)}" ${b.plus.includes(p)?'checked':''}>${esc(E.title(p))}+</label>`).join('')||'<p>Signature upgrades begin at level 30.</p>'}</div>`;}
 if(tab==='facilities'){html=`<div class="body-controls"><label>Club level<input id="club-level" type="number" min="1" max="10" value="${b.clubLevel}"></label><label>Facilities<select id="facility-mode">${options(['planned','active'],b.facilityMode)}</select></label>${lock('facilities')}<span class="metric">${(f.budget-f.cost).toLocaleString()}<small> club budget left</small></span></div><p class="muted">${b.facilityMode==='active'?'Your actual club facilities. The adviser cannot change them.':'Plan facilities for the whole club. These are proposed boosts until your club equips them.'}</p><div class="cards">`+d.facilities.map(f=>`<div class="choice facility"><div><strong>${esc(f.name)}</strong><p>${f.levels.map(l=>`L${l.level}: ${l.cost.toLocaleString()}`).join(' · ')}</p><p>${Object.entries(f.levels.find(l=>l.level===b.facilities[f.name])?.boosts||{}).map(([k,v])=>`${esc(E.title(k))} +${v}`).join(' · ')}</p><p>${(()=>{const l=f.levels.find(l=>l.level===b.facilities[f.name]);return l?.regular?esc(E.title(l.regular))+' bonus PlayStyle':l?.plus?esc(E.title(l.plus))+'+ bonus PlayStyle':'';})()}</p></div><select aria-label="${esc(f.name)} level" data-facility="${esc(f.name)}"><option value="0">Off</option>${options(f.levels.map(l=>l.level),b.facilities[f.name])}</select></div>`).join('')+'</div>';}
 if(tab==='running'){html=`<p class="muted">Compare Mufasa Gaming’s 23 animation references. Visual resemblance and AcceleRATE are separate; a style name is not evidence of a speed bonus.</p><div id="video"></div><div class="run-grid">`+runs.map((r,i)=>`<div class="run-card"><strong>${esc(r.name)}</strong><button data-watch="${i}">Preview animation ↗</button><button data-run="${esc(r.name)}" ${b.runStyle===r.name?'class="primary"':''}>${b.runStyle===r.name?'Selected':'Use this style'}</button><a href="${esc(r.url)}" target="_blank" rel="noreferrer">Mufasa Gaming source ↗</a></div>`).join('')+'</div>';}
 if(tab==='evidence')html=`<div class="notice">Reference snapshot: 13 Sep 2026. Community calculator data is not independently certified. Enable “Look up sources online” in chat for fresh research. New findings are treated as evidence to assess, not automatic calculator rules.</div>`+evidence.map(e=>`<article class="card evidence"><span class="badge">${esc(e.confidence)} · ${esc(e.scope)}</span><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><a href="${esc(e.url)}" target="_blank" rel="noreferrer">Read source ↗</a></article>`).join('');
 $('#editor').innerHTML=html;
 document.querySelectorAll('[data-lock]').forEach(el=>el.onclick=()=>change(n=>{const k=el.dataset.lock;n.locks=n.locks.includes(k)?n.locks.filter(x=>x!==k):[...n.locks,k];}));
 document.querySelectorAll('[data-attr]').forEach(el=>el.onchange=()=>change(n=>{const k=el.dataset.attr,v=Number(el.value),r=a.attributeRanges[k];if(!Number.isInteger(v)||v<r.min||v>r.max)throw Error(`${E.title(k)} must be ${r.min}–${r.max}.`);n.attributes[k]=v;}));
 for(const [selector,key]of [['[data-style]','playstyles'],['[data-plus]','plus']])document.querySelectorAll(selector).forEach(el=>el.onchange=()=>change(n=>{const v=el.dataset.style||el.dataset.plus;n[key]=el.checked?[...n[key],v]:n[key].filter(p=>p!==v);}));
 if($('#specialization'))$('#specialization').onchange=e=>change(n=>n.specialization=e.target.value);
 if($('#club-level'))$('#club-level').onchange=e=>change(n=>{const v=Number(e.target.value);if(!Number.isInteger(v)||v<1||v>10)throw Error('Club level must be 1–10.');n.clubLevel=v;});
 if($('#facility-mode'))$('#facility-mode').onchange=e=>change(n=>n.facilityMode=e.target.value);
 document.querySelectorAll('[data-facility]').forEach(el=>el.onchange=()=>change(n=>{if(+el.value)n.facilities[el.dataset.facility]=+el.value;else delete n.facilities[el.dataset.facility];}));
 document.querySelectorAll('[data-run]').forEach(el=>el.onclick=()=>change(n=>n.runStyle=el.dataset.run));
 document.querySelectorAll('[data-watch]').forEach(el=>el.onclick=()=>{const r=runs[+el.dataset.watch],url=new URL(r.embed);url.searchParams.set('autoplay','0');url.searchParams.set('background','0');url.searchParams.set('controls','1');$('#video').innerHTML=`<iframe class="video-frame" title="${esc(r.name)} running animation" src="${esc(url.href)}" allow="fullscreen; picture-in-picture" allowfullscreen></iframe><p><a href="${esc(r.url)}" target="_blank" rel="noreferrer">Watch ${esc(r.name)} on Mufasa Gaming if the embed is unavailable ↗</a></p>`;});
}
function message(role,text){const el=document.createElement('article');el.className=`message ${role}`;el.textContent=text;$('#messages').append(el);$('#messages').scrollTop=$('#messages').scrollHeight;return el;}
$('#tabs').onclick=e=>{if(!e.target.dataset.tab)return;tab=e.target.dataset.tab;$('#tabs .active')?.classList.remove('active');e.target.classList.add('active');render();};
$('#build-name').onchange=e=>change(n=>n.name=e.target.value.slice(0,80)||'My build');
$('#undo').onclick=()=>{if(history.length){b=history.pop();revision++;render();}};
$('#save').onclick=()=>{try{localStorage.setItem('fc26-build',JSON.stringify(b));status('Saved on this browser. Export a file to keep a portable copy.');}catch{status('Browser storage is unavailable. Use Export instead.');}};
function parseBuild(text){if(text.length>50000)throw Error('Build file is too large.');const parsed=JSON.parse(text);const next={...E.fresh(d,parsed.archetype),...parsed};if(typeof next.runStyle!=='string'||!runs.some(r=>r.name===next.runStyle)&&next.runStyle!=='')throw Error('Unknown running style.');if(!Array.isArray(next.locks)||next.locks.some(k=>typeof k!=='string'))throw Error('Invalid locks.');if(typeof next.name!=='string'||next.name.length>80)throw Error('Invalid build name.');commit(next);}
$('#load').onclick=()=>{try{const raw=localStorage.getItem('fc26-build');if(!raw)throw Error('No saved build on this browser yet.');parseBuild(raw);}catch(e){status(e.message);}};
$('#export').onclick=()=>{const link=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));link.href=url;link.download='fc26-build.json';link.click();URL.revokeObjectURL(url);};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(file)parseBuild(await file.text());}catch(e){status(`Import failed: ${e.message}`);}finally{e.target.value='';}};
$('#settings').onclick=()=>{$('#endpoint').value=endpoint;$('#connection').showModal();};
$('#connect').onclick=async()=>{try{const url=new URL($('#endpoint').value);if(url.protocol!=='https:'&&!['localhost','127.0.0.1'].includes(url.hostname))throw Error('Use an HTTPS backend URL.');endpoint=url.origin;teamCode=$('#team-code').value;localStorage.setItem('fc26-endpoint',endpoint);$('#chat-state').textContent='Connection configured';$('#connection-status').textContent='Saved. Send a message to test the connection.';$('#settings').textContent='Chat settings';$('#connection').close();}catch(e){$('#connection-status').textContent=e.message;}};
$('#clear-chat').onclick=()=>{chatHistory=[];$('#messages').replaceChildren();message('assistant','Conversation cleared. Your build is unchanged.');};
document.querySelectorAll('[data-prompt]').forEach(el=>el.onclick=()=>{$('#prompt').value=el.dataset.prompt;$('#prompt').focus();});
$('#chat-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const text=$('#prompt').value.trim();if(!text)return;if(!endpoint){$('#settings').click();return;}busy=true;$('#send').disabled=true;$('#chat-state').textContent='Thinking…';$('#prompt').value='';message('user',text);const baseRevision=revision,base=structuredClone(b),apply=$('#auto-apply').checked;const pending=message('assistant','Checking your build and the evidence…');try{const response=await fetch(endpoint+'/chat',{method:'POST',headers:{'Content-Type':'application/json','X-Team-Code':teamCode},body:JSON.stringify({message:text,build:base,history:chatHistory.slice(-8),research:$('#research').checked}),signal:AbortSignal.timeout(90000)});const result=await response.json();if(!response.ok)throw Error(result.error||'Chat is unavailable.');pending.textContent=result.reply;chatHistory.push({role:'user',text},{role:'model',text:result.reply});if(result.build){const next=result.build;const differences=Object.keys(base.attributes).filter(k=>next.attributes[k]!==base.attributes[k]).map(k=>`${E.title(k)} ${base.attributes[k]} → ${next.attributes[k]}`);const summary=document.createElement('small');summary.textContent='\nProposed build: '+next.archetype+' · '+differences.join(', ');pending.append(summary);const applyBuild=()=>{if(revision!==baseRevision)throw Error('Your build changed since this reply. Ask the adviser to update its proposal.');commit(E.applyChanges(d,b,Object.fromEntries(['name','archetype','attributes','skillMoves','weakFoot','height','weight','gender','playstyles','plus','specialization','facilities','runStyle'].map(k=>[k,next[k]]))));};if(apply&&result.action==='apply'&&revision===baseRevision){applyBuild();pending.append(document.createTextNode('\nApplied to your editor. Undo is available.'));}else{const button=document.createElement('button');button.textContent='Apply this build';button.onclick=()=>{try{applyBuild();button.disabled=true;button.textContent='Applied';}catch(err){status(err.message);}};pending.append(button);}}$('#chat-state').textContent='Connected';}catch(err){pending.textContent=err.name==='TimeoutError'?'The adviser took too long. Your build is unchanged. Try again.':err.message;$('#chat-state').textContent='Connection needs attention';}finally{busy=false;$('#send').disabled=false;$('#messages').scrollTop=$('#messages').scrollHeight;}};
try{[d,runs,evidence]=await Promise.all(['game','runs','evidence'].map(async f=>{const r=await fetch(`./data/${f}.json`);if(!r.ok)throw Error('Unable to load game reference.');return r.json();}));b=E.fresh(d);render();}catch(e){$('#editor').textContent=e.message;}
