export const normalize = s => String(s).toLowerCase().replace(/[^a-z0-9]/g, '');
export const title = s => String(s).replace(/([a-z])([A-Z])/g,'$1 $2').replace(/\b\w/g,c=>c.toUpperCase());
export function archetype(d,b){const a=d.archetypes.find(a=>a.name===b.archetype);if(!a)throw Error('Unknown archetype');return a;}
export function bodySizes(d,b,field){
 if(!['height','weight'].includes(field))throw Error('Unknown body measurement.');
 const pairs=Object.keys(d.body[archetype(d,b).name.toLowerCase()]).map(k=>k.split('-').map(Number));
 const index=field==='height'?0:1,other=field==='height'?b.weight:b.height;
 return [...new Set(pairs.filter(p=>p[1-index]===other).map(p=>p[index]))].sort((a,b)=>a-b);
}
export function setBodySize(d,b,field,value){
 if(!Number.isInteger(value)||!bodySizes(d,b,field).includes(value))throw Error(`Choose a supported ${field} for ${b.archetype}.`);
 return {...b,[field]:value};
}
export function fresh(d,name='Magician',level=100){const a=archetype(d,{archetype:name});return {version:1,name:'My build',archetype:name,level,attributes:Object.fromEntries(Object.entries(a.attributeRanges).map(([k,v])=>[k,v.min])),skillMoves:a.skillMoveRating.base,weakFoot:a.weakFootRating.base,height:d.bodyDefaults[name].heightCm,weight:d.bodyDefaults[name].weightKg,gender:'male',playstyles:[],plus:[],specialization:'',facilities:{},clubLevel:10,facilityMode:'planned',runStyle:'',locks:[]};}
export const budget=(d,b)=>d.levels.filter(l=>l.level<=b.level).reduce((s,l)=>s+l.apReward,0);
export function attributeCost(d,b,key,value=b.attributes[key]){const r=archetype(d,b).attributeRanges[key];let tier=b.archetype==='Target'&&key==='Strength'?3:d.tiers[key];tier=Math.max(0,tier-(r.isKeyAttribute?1:0));let cost=0;for(let n=r.min+1;n<=value;n++){const band=n<55?'50-54':n<=60?'55-60':n<=63?'61-63':n<=66?'64-66':n<=69?'67-69':n<=74?'70-74':n<=79?'75-79':n<=84?'80-84':n<=89?'85-89':n<=94?'90-94':String(n);cost+=d.costs[tier][band];}return cost;}
export const spent=(d,b)=>Object.keys(archetype(d,b).attributeRanges).reduce((s,k)=>s+attributeCost(d,b,k),0)+(d.stars[b.archetype].skillMoves[b.skillMoves]||0)+(d.stars[b.archetype].weakFoot[b.weakFoot]||0);
export function facilities(d,b){let cost=0;const boosts={},regular=[],plus=[];for(const [name,l]of Object.entries(b.facilities)){const f=d.facilities.find(f=>f.name===name)?.levels.find(v=>v.level===l);if(!f)continue;cost+=f.cost;for(const [k,v]of Object.entries(f.boosts))boosts[k]=(boosts[k]||0)+v;if(f.regular)regular.push(f.regular);if(f.plus)plus.push(f.plus);}return {cost,boosts,regular,plus,budget:d.clubBudgets.find(c=>c.level===b.clubLevel)?.budget||0};}
export function body(d,b){const table=d.body[b.archetype.toLowerCase()];const exact=table?.[`${b.height}-${b.weight}`];if(exact)return {boosts:exact,exact:true};let distance=Infinity,boosts={};for(const [key,v]of Object.entries(table||{})){const [h,w]=key.split('-').map(Number);const dist=(h-b.height)**2+(w-b.weight)**2;if(dist<distance){distance=dist;boosts=v;}}return {boosts,exact:false};}
export function effective(d,b){const bo=body(d,b).boosts,f=facilities(d,b).boosts;return Object.fromEntries(Object.entries(b.attributes).map(([k,v])=>[k,Math.max(1,Math.min(99,v+(bo[k]||0)+(f[k]||0)))]));}
export function accelerate(d,b){const a=effective(d,b),h=b.gender==='female'?b.height+20:b.height;return a.Agility>=65&&a.Agility-a.Strength>=10&&a.Acceleration>=80&&h<=182?'Explosive':a.Strength>=65&&a.Strength-a.Agility>=4&&a.Acceleration>=40&&h>=185?'Lengthy':'Controlled';}
export function requirements(b,item){return (item?.attributeRequirements||[]).filter(r=>!(b.attributes[r.attribute]>=r.minimumValue));}
export const slots=(d,b)=>d.meta.playstyleSlotUnlockLevels.filter(l=>l<=b.level).length;
export const plusSlots=(d,b)=>d.meta.playstylePlusUpgradeLevels.filter(l=>l<=b.level).length;
export function plusOptions(d,b){const a=archetype(d,b);const result=Object.values(a.playstylePlusProgression).slice(0,plusSlots(d,b));const sp=a.specializationPerks.find(s=>s.specializationName===b.specialization);if(sp&&!requirements(b,sp).length)result.push(sp.unlocksAtPlaystylePlus);return result;}
export function validate(d,b){const errors=[];let a;try{a=archetype(d,b);}catch{return ['Unknown archetype'];}if(!Number.isInteger(b.level)||b.level<1||b.level>100)errors.push('Level must be 1–100.');for(const [k,r]of Object.entries(a.attributeRanges))if(!Number.isInteger(b.attributes?.[k])||b.attributes[k]<r.min||b.attributes[k]>r.max)errors.push(`${title(k)} must be ${r.min}–${r.max}.`);if(errors.length)return errors;
 for(const [k,r]of [['skillMoves',a.skillMoveRating],['weakFoot',a.weakFootRating]])if(!Number.isInteger(b[k])||b[k]<r.base||b[k]>r.max)errors.push(`${title(k)} is outside this archetype's range.`);
 const points=spent(d,b);if(points>budget(d,b))errors.push(`Over AP budget by ${points-budget(d,b)}.`);
 const table=d.body[b.archetype.toLowerCase()];if(!Number.isInteger(b.height)||!Number.isInteger(b.weight)||!table?.[`${b.height}-${b.weight}`])errors.push('Choose a height and weight combination in the reference table.');if(!['male','female'].includes(b.gender))errors.push('Unknown body category.');
 if(!Array.isArray(b.playstyles)||!Array.isArray(b.plus))return [...errors,'Invalid PlayStyle selection.'];if(new Set(b.playstyles.map(normalize)).size!==b.playstyles.length)errors.push('Duplicate PlayStyles.');if(b.playstyles.length>slots(d,b))errors.push(`Only ${slots(d,b)} regular slots available.`);
 for(const name of b.playstyles){const p=d.playstyles.find(p=>normalize(p.name)===normalize(name));if(!p)errors.push(`Unknown PlayStyle: ${name}`);else if(normalize(name)!==normalize(a.basePlaystyle)&&requirements(b,p).length)errors.push(`${title(name)} requirements not met.`);}
 const sp=a.specializationPerks.find(s=>s.specializationName===b.specialization);if(b.specialization&&(!sp||requirements(b,sp).length))errors.push('Specialization requirements not met.');if(b.plus.length>plusSlots(d,b))errors.push('Too many signature PlayStyles+.');if(new Set(b.plus.map(normalize)).size!==b.plus.length)errors.push('Duplicate PlayStyles+.');for(const p of b.plus)if(!plusOptions(d,b).some(x=>normalize(x)===normalize(p)))errors.push(`Unavailable signature PlayStyle+: ${p}`);
 if(!Number.isInteger(b.clubLevel)||b.clubLevel<1||b.clubLevel>10)errors.push('Club level must be 1–10.');for(const [name,l]of Object.entries(b.facilities||{}))if(!d.facilities.find(f=>f.name===name)?.levels.some(v=>v.level===l))errors.push(`Invalid facility: ${name}`);if(facilities(d,b).cost>facilities(d,b).budget)errors.push('Facilities exceed the club budget.');if(!['planned','active'].includes(b.facilityMode))errors.push('Invalid facility mode.');return errors;}
export function applyChanges(d,current,patch){if(!patch||typeof patch!=='object'||Array.isArray(patch))throw Error('Invalid build changes.');const allowed=['name','archetype','attributes','skillMoves','weakFoot','height','weight','gender','playstyles','plus','specialization','facilities','runStyle'];for(const k of Object.keys(patch))if(!allowed.includes(k))throw Error(`The adviser cannot change ${k}.`);let next=structuredClone(current);if(patch.archetype&&patch.archetype!==current.archetype){if(current.locks.length)throw Error('Unlock your choices before changing archetype.');next={...fresh(d,patch.archetype,current.level),clubLevel:current.clubLevel,facilities:current.facilities,facilityMode:current.facilityMode};}for(const [k,v]of Object.entries(patch)){if(k==='attributes'){for(const [a,n]of Object.entries(v)){if(!Object.hasOwn(next.attributes,a))throw Error(`Unknown attribute ${a}`);if(current.locks.includes(a)&&n!==current.attributes[a])throw Error(`${title(a)} is locked.`);next.attributes[a]=n;}}else{if(current.locks.includes(k)&&JSON.stringify(v)!==JSON.stringify(current[k]))throw Error(`${title(k)} is locked.`);if(k==='facilities'&&current.facilityMode==='active'&&JSON.stringify(v)!==JSON.stringify(current.facilities))throw Error('Active club facilities are fixed. Switch to planning mode to change them.');next[k]=v;}}const errors=validate(d,next);if(errors.length)throw Error(errors.join(' '));return next;}
export function optimize(d,current,plan){let b=plan.archetype&&plan.archetype!==current.archetype?applyChanges(d,current,{archetype:plan.archetype}):structuredClone(current);const weights=plan.priorities||{};for(const [k,v]of Object.entries(weights))if(!Object.hasOwn(b.attributes,k)||!Number.isFinite(v)||v<0||v>10)throw Error('Invalid attribute priorities.');
 const targets=plan.targets||{};for(const [k,v]of Object.entries(targets))if(!Object.hasOwn(b.attributes,k)||!Number.isInteger(v))throw Error('Invalid attribute targets.');
 if(plan.resetAttributes){for(const [k,r]of Object.entries(archetype(d,b).attributeRanges))if(!b.locks.includes(k))b.attributes[k]=r.min;b.playstyles=[];b.plus=[];b.specialization='';}
 for(const [k,t]of Object.entries(targets)){if(b.locks.includes(k))continue;b.attributes[k]=Math.max(archetype(d,b).attributeRanges[k].min,Math.min(archetype(d,b).attributeRanges[k].max,t));}
 if(spent(d,b)>budget(d,b))throw Error('Requested targets exceed the AP budget. Reduce targets or unlock attributes.');
 for(let i=0;i<3000;i++){let best=null,score=0;const left=budget(d,b)-spent(d,b);for(const [k,r]of Object.entries(archetype(d,b).attributeRanges)){if(b.locks.includes(k)||b.attributes[k]>=r.max)continue;const cost=attributeCost(d,b,k,b.attributes[k]+1)-attributeCost(d,b,k);const utility=(weights[k]||0)/(cost*(1+(b.attributes[k]-r.min)/20));if(cost<=left&&utility>score){score=utility;best=k;}}if(!best)break;b.attributes[best]++;}
 if(plan.patch)b=applyChanges(d,b,plan.patch);
 const errors=validate(d,b);if(errors.length)throw Error(errors.join(' '));return b;}
